# Generated by Codex on 2026-02-10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_choice_choice_es_choice_choice_fr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiResponseQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='quiz.question')),
                ('choice_order', models.CharField(blank=True, choices=[('content', 'Content'), ('random', 'Random'), ('none', 'None')], help_text='The order in which multichoice choice options are displayed to the user', max_length=30, null=True, verbose_name='Choice Order')),
            ],
            options={
                'verbose_name': 'Multi Response Question',
                'verbose_name_plural': 'Multi Response Questions',
            },
            bases=('quiz.question',),
        ),
        migrations.CreateModel(
            name='MultiResponseChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(help_text='Enter the choice text that you want displayed', max_length=1000, verbose_name='Content')),
                ('correct', models.BooleanField(default=False, help_text='Is this a correct answer?', verbose_name='Correct')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.multiresponsequestion', verbose_name='Question')),
            ],
            options={
                'verbose_name': 'Multi Response Choice',
                'verbose_name_plural': 'Multi Response Choices',
            },
        ),
    ]
