# Generated by Codex on 2026-02-10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_multi_response_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrueFalseQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='quiz.question')),
            ],
            options={
                'verbose_name': 'True/False Question',
                'verbose_name_plural': 'True/False Questions',
            },
            bases=('quiz.question',),
        ),
        migrations.CreateModel(
            name='TrueFalseStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.CharField(help_text='Enter the statement text that you want displayed', max_length=1000, verbose_name='Statement')),
                ('correct', models.BooleanField(default=False, help_text='Is this statement true?', verbose_name='Correct')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.truefalsequestion', verbose_name='Question')),
            ],
            options={
                'verbose_name': 'True/False Statement',
                'verbose_name_plural': 'True/False Statements',
            },
        ),
    ]
